title: Whiskey
email: sam@nothingmagical.com
author: Nothing Magical Inc.
baseurl: ""
url: https://usewhiskey.com
timezone: America/Los_Angeles
encoding: utf-8
strict_front_matter: true
exclude:
  - README.md
permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
