name: Ruby
on:
  pull_request:
    paths:
      - '**/*.rb'
      - '**/*.ru'
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - .github/workflows/ruby.yml
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bundle exec rake lint:ruby
